site_name: LITEPODS - Links to Everything PODS
site_description: LInks To Everything PODS
site_url: https://bsc-iitm.github.io/litepods

# Repository
repo_name: bsc-iitm/litepods
repo_url: https://github.com/bsc-iitm/litepods
edit_uri: edit/unstable/docs/

theme:
  name: material
  # custom_dir: overrides
  favicon: assets/logo.svg
  logo: assets/logo.svg

  #shortcuts
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  highlightjs: true

  #when editing a page
  theme:
  icon:
    edit: material/pencil 
    view: material/eye

  palette:
    #light mode
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    #dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    # - navigation.footer
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    # - toc.integrate 


markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - def_list
  - toc:
      title: On this Page
      toc_depth: 2
      permalink: true
      permalink_title: Copy link to this section for reference
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition


plugins:
  - blog:
      post_date_format: full
      blog_dir: blog
      # post_dir: "{blog}/articles"
      archive_date_format: MMMM yyyy
      post_readtime: true
      blog_toc: true
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - minify:
      minify_html: true

extra:
  analytics:
    # provider: google
    # property:
  generator: false

#site navigation

nav:
  - Home:
      index.md
  - For Everyone:
      everyone/index.md
  - Foundation:
      foundation/index.md
  - Diploma Programming:
      diploma_programming/index.md
  - Diploma Data Science:
      diploma_data-science/index.md
  - BSc:
      bsc/index.md
  - BS:
      bs/index.md