site_name: LITEPODS - Links to Everything PODS
site_description: LInks To Everything PODS
site_url: https://bsc-iitm.github.io/litepods

# Repository
repo_name: bsc-iitm/litepods
repo_url: https://github.com/bsc-iitm/litepods
edit_uri: edit/unstable/docs/

theme:
  name: material
  # custom_dir: overrides
  favicon: assets/logo.svg
  logo: assets/logo.svg

  #shortcuts
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  highlightjs: true

  #when editing a page
  theme:
  # icon:
  #   edit: material/pencil 
  #   view: material/eye

  palette:
    #light mode
    - scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    #dark mode
    - scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    # - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    # - toc.integrate 


markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - def_list
  - toc:
      title: On this Page
      toc_depth: 2
      permalink: true
      permalink_title: Copy link to this section for reference
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition


plugins:
  - blog:
      archive: false
      categories: false
      post_date_format: full
      blog_dir: updates
      # post_dir: "{blog}/articles"
      archive_date_format: MMMM yyyy
      post_readtime: true
      blog_toc: true
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - minify:
      minify_html: true

extra:
  analytics:
    # provider: google
    # property:
  generator: false

#site navigation

nav:
  - For Everyone: 
      - Official: everyone/official.md
      - Unofficial: everyone/unofficial.md
      - Paradox: everyone/paradox.md
  - Foundation:
      - Maths 1: foundation/maths_1.md
      - Stats 1: foundation/stats_1.md
      - CT: foundation/ct.md
      - Python: foundation/python.md
      - Maths 2: foundation/maths_2.md
      - Stats 2: foundation/stats_2.md
      - English 1: foundation/english_1.md
      - English 2: foundation/english_2.md
      
  - Diploma Programming:
      - Courses:
          - PDSA: diploma_programming/pdsa.md
          - MAD 1: diploma_programming/mad_1.md
          - MAD 2: diploma_programming/mad_2.md
          - DBMS: diploma_programming/dbms.md
          - System Commands: diploma_programming/system_commands.md
          - JAVA: diploma_programming/java.md
      - Projects: 
          - MAD 1 - Project: diploma_programming/mad_1_project.md
          - MAD 2 - Project: diploma_programming/mad_2_project.md

  - Diploma Data Science:
      - Courses:
          - Machine Learning Foundations: diploma_ds/mlf.md
          - Machine Learning Techniques: diploma_ds/mlt.md
          - Machine Learning Practice: diploma_ds/mlp.md
          - Business Analytics: diploma_ds/ba.md
          - Business Data Management: diploma_ds/bdm.md
          - Tools in Data Science: diploma_ds/tds.md
      - Projects:
          - Machine Learning Practice - Project: diploma_ds/mlp_project.md
          - Business Data Management - Project: diploma_ds/bdm_project.md
  - BSc:
      bsc/index.md
  - BS:
      bs/index.md
  - How to Contribute: contribute/index.html
  - Updates: updates/index.html
